// GENERATED BY `pnpm sync` — DO NOT EDIT.
// Source of truth is the folder layout under src/trees/.
// Regenerate with: pnpm sync

import type { ForestComponent, SpeciesNode } from "@/lib/forest";

import { meta as species_chromeMeta } from "./chrome/species.meta";
import { meta as chrome_pageNavMeta } from "./chrome/page-nav/tree.meta";
import * as chrome_pageNavFixtures from "./chrome/page-nav/page-nav.fixtures";
import { meta as chrome_pageNav_canonMeta } from "./chrome/page-nav/branches/canon/branch.meta";
import { PageNavBrandBar as chrome_pageNav_canon_brandBar, meta as chrome_pageNav_canon_brandBarMeta } from "./chrome/page-nav/branches/canon/brand-bar/brand-bar";
import { PageNavGlassTrack as chrome_pageNav_canon_glassTrack, meta as chrome_pageNav_canon_glassTrackMeta } from "./chrome/page-nav/branches/canon/glass-track/glass-track";
import { PageNavPillTrack as chrome_pageNav_canon_pillTrack, meta as chrome_pageNav_canon_pillTrackMeta } from "./chrome/page-nav/branches/canon/pill-track/pill-track";
import { meta as chrome_pageNav_experimentalMeta } from "./chrome/page-nav/branches/experimental/branch.meta";
import { PageNavFloatingCapsule as chrome_pageNav_experimental_floatingCapsule, meta as chrome_pageNav_experimental_floatingCapsuleMeta } from "./chrome/page-nav/branches/experimental/floating-capsule/floating-capsule";
import { meta as chrome_paneDockMeta } from "./chrome/pane-dock/tree.meta";
import * as chrome_paneDockFixtures from "./chrome/pane-dock/pane-dock.fixtures";
import { meta as chrome_paneDock_canonMeta } from "./chrome/pane-dock/branches/canon/branch.meta";
import { PaneDockDoorRow as chrome_paneDock_canon_doorRow, meta as chrome_paneDock_canon_doorRowMeta } from "./chrome/pane-dock/branches/canon/door-row/door-row";
import { PaneDockEdgeStrips as chrome_paneDock_canon_edgeStrips, meta as chrome_paneDock_canon_edgeStripsMeta } from "./chrome/pane-dock/branches/canon/edge-strips/edge-strips";
import { PaneDockOneRail as chrome_paneDock_canon_oneRail, meta as chrome_paneDock_canon_oneRailMeta } from "./chrome/pane-dock/branches/canon/one-rail/one-rail";
import { meta as chrome_paneDock_experimentalMeta } from "./chrome/pane-dock/branches/experimental/branch.meta";
import { PaneDockCommandSheet as chrome_paneDock_experimental_commandSheet, meta as chrome_paneDock_experimental_commandSheetMeta } from "./chrome/pane-dock/branches/experimental/command-sheet/command-sheet";
import { meta as chrome_sectionTabsMeta } from "./chrome/section-tabs/tree.meta";
import * as chrome_sectionTabsFixtures from "./chrome/section-tabs/section-tabs.fixtures";
import { meta as chrome_sectionTabs_canonMeta } from "./chrome/section-tabs/branches/canon/branch.meta";
import { SectionTabsPopoverMenu as chrome_sectionTabs_canon_popoverMenu, meta as chrome_sectionTabs_canon_popoverMenuMeta } from "./chrome/section-tabs/branches/canon/popover-menu/popover-menu";
import { SectionTabsSideRail as chrome_sectionTabs_canon_sideRail, meta as chrome_sectionTabs_canon_sideRailMeta } from "./chrome/section-tabs/branches/canon/side-rail/side-rail";
import { SectionTabsTopTrack as chrome_sectionTabs_canon_topTrack, meta as chrome_sectionTabs_canon_topTrackMeta } from "./chrome/section-tabs/branches/canon/top-track/top-track";
import { meta as chrome_sectionTabs_experimentalMeta } from "./chrome/section-tabs/branches/experimental/branch.meta";
import { SectionTabsHoverDock as chrome_sectionTabs_experimental_hoverDock, meta as chrome_sectionTabs_experimental_hoverDockMeta } from "./chrome/section-tabs/branches/experimental/hover-dock/hover-dock";
import { meta as species_commerceMeta } from "./commerce/species.meta";
import { meta as commerce_productCardMeta } from "./commerce/product-card/tree.meta";
import * as commerce_productCardFixtures from "./commerce/product-card/product-card.fixtures";
import { meta as commerce_productCard_canonMeta } from "./commerce/product-card/branches/canon/branch.meta";
import { ProductCardDetailRow as commerce_productCard_canon_detailRow, meta as commerce_productCard_canon_detailRowMeta } from "./commerce/product-card/branches/canon/detail-row/detail-row";
import { ProductCardSpecShelf as commerce_productCard_canon_specShelf, meta as commerce_productCard_canon_specShelfMeta } from "./commerce/product-card/branches/canon/spec-shelf/spec-shelf";
import { meta as commerce_productCard_experimentalMeta } from "./commerce/product-card/branches/experimental/branch.meta";
import { ProductCardPriceTag as commerce_productCard_experimental_priceTag, meta as commerce_productCard_experimental_priceTagMeta } from "./commerce/product-card/branches/experimental/price-tag/price-tag";
import { meta as species_disclosureMeta } from "./disclosure/species.meta";
import { meta as disclosure_expandableCardMeta } from "./disclosure/expandable-card/tree.meta";
import * as disclosure_expandableCardFixtures from "./disclosure/expandable-card/expandable-card.fixtures";
import { meta as disclosure_expandableCard_canonMeta } from "./disclosure/expandable-card/branches/canon/branch.meta";
import { ExpandableCardInlineDetail as disclosure_expandableCard_canon_inlineDetail, meta as disclosure_expandableCard_canon_inlineDetailMeta } from "./disclosure/expandable-card/branches/canon/inline-detail/inline-detail";
import { ExpandableCardMediaGrid as disclosure_expandableCard_canon_mediaGrid, meta as disclosure_expandableCard_canon_mediaGridMeta } from "./disclosure/expandable-card/branches/canon/media-grid/media-grid";
import { ExpandableCardRowList as disclosure_expandableCard_canon_rowList, meta as disclosure_expandableCard_canon_rowListMeta } from "./disclosure/expandable-card/branches/canon/row-list/row-list";
import { meta as disclosure_expandableCard_experimentalMeta } from "./disclosure/expandable-card/branches/experimental/branch.meta";
import { ExpandableCardFullBleed as disclosure_expandableCard_experimental_fullBleed, meta as disclosure_expandableCard_experimental_fullBleedMeta } from "./disclosure/expandable-card/branches/experimental/full-bleed/full-bleed";
import { meta as species_findingMeta } from "./finding/species.meta";
import { meta as finding_clipPickerMeta } from "./finding/clip-picker/tree.meta";
import * as finding_clipPickerFixtures from "./finding/clip-picker/clip-picker.fixtures";
import { meta as finding_clipPicker_canonMeta } from "./finding/clip-picker/branches/canon/branch.meta";
import { ClipPickerOneColumn as finding_clipPicker_canon_oneColumn, meta as finding_clipPicker_canon_oneColumnMeta } from "./finding/clip-picker/branches/canon/one-column/one-column";
import { ClipPickerQuoteFirst as finding_clipPicker_canon_quoteFirst, meta as finding_clipPicker_canon_quoteFirstMeta } from "./finding/clip-picker/branches/canon/quote-first/quote-first";
import { ClipPickerShelfRail as finding_clipPicker_canon_shelfRail, meta as finding_clipPicker_canon_shelfRailMeta } from "./finding/clip-picker/branches/canon/shelf-rail/shelf-rail";
import { meta as finding_clipPicker_experimentalMeta } from "./finding/clip-picker/branches/experimental/branch.meta";
import { ClipPickerDeck as finding_clipPicker_experimental_deck, meta as finding_clipPicker_experimental_deckMeta } from "./finding/clip-picker/branches/experimental/deck/deck";
import { meta as species_landingMeta } from "./landing/species.meta";
import { meta as landing_channelHeroMeta } from "./landing/channel-hero/tree.meta";
import * as landing_channelHeroFixtures from "./landing/channel-hero/channel-hero.fixtures";
import { meta as landing_channelHero_broadcastMeta } from "./landing/channel-hero/branches/broadcast/branch.meta";
import { ChannelHeroLiveMarquee as landing_channelHero_broadcast_liveMarquee, meta as landing_channelHero_broadcast_liveMarqueeMeta } from "./landing/channel-hero/branches/broadcast/live-marquee/live-marquee";
import { meta as landing_channelHero_canonMeta } from "./landing/channel-hero/branches/canon/branch.meta";
import { ChannelHeroSplitDock as landing_channelHero_canon_splitDock, meta as landing_channelHero_canon_splitDockMeta } from "./landing/channel-hero/branches/canon/split-dock/split-dock";
import { ChannelHeroStackedBillboard as landing_channelHero_canon_stackedBillboard, meta as landing_channelHero_canon_stackedBillboardMeta } from "./landing/channel-hero/branches/canon/stacked-billboard/stacked-billboard";
import { meta as species_motionMeta } from "./motion/species.meta";
import { meta as motion_auroraHeadlineMeta } from "./motion/aurora-headline/tree.meta";
import * as motion_auroraHeadlineFixtures from "./motion/aurora-headline/aurora-headline.fixtures";
import { meta as motion_auroraHeadline_canonMeta } from "./motion/aurora-headline/branches/canon/branch.meta";
import { AuroraHeadlineBaseline as motion_auroraHeadline_canon_baseline, meta as motion_auroraHeadline_canon_baselineMeta } from "./motion/aurora-headline/branches/canon/baseline/baseline";
import { AuroraHeadlineStackedRule as motion_auroraHeadline_canon_stackedRule, meta as motion_auroraHeadline_canon_stackedRuleMeta } from "./motion/aurora-headline/branches/canon/stacked-rule/stacked-rule";
import { meta as motion_auroraHeadline_experimentalMeta } from "./motion/aurora-headline/branches/experimental/branch.meta";
import { AuroraHeadlineOrbitGlow as motion_auroraHeadline_experimental_orbitGlow, meta as motion_auroraHeadline_experimental_orbitGlowMeta } from "./motion/aurora-headline/branches/experimental/orbit-glow/orbit-glow";
import { meta as species_narrativeMeta } from "./narrative/species.meta";
import { meta as narrative_stepRevealMeta } from "./narrative/step-reveal/tree.meta";
import * as narrative_stepRevealFixtures from "./narrative/step-reveal/step-reveal.fixtures";
import { meta as narrative_stepReveal_canonMeta } from "./narrative/step-reveal/branches/canon/branch.meta";
import { StepRevealNumberedRail as narrative_stepReveal_canon_numberedRail, meta as narrative_stepReveal_canon_numberedRailMeta } from "./narrative/step-reveal/branches/canon/numbered-rail/numbered-rail";
import { StepRevealWideCards as narrative_stepReveal_canon_wideCards, meta as narrative_stepReveal_canon_wideCardsMeta } from "./narrative/step-reveal/branches/canon/wide-cards/wide-cards";
import { meta as narrative_stepReveal_experimentalMeta } from "./narrative/step-reveal/branches/experimental/branch.meta";
import { StepRevealStageSwap as narrative_stepReveal_experimental_stageSwap, meta as narrative_stepReveal_experimental_stageSwapMeta } from "./narrative/step-reveal/branches/experimental/stage-swap/stage-swap";
import { meta as species_temporalMeta } from "./temporal/species.meta";
import { meta as temporal_countdownMeta } from "./temporal/countdown/tree.meta";
import * as temporal_countdownFixtures from "./temporal/countdown/countdown.fixtures";
import { meta as temporal_countdown_canonMeta } from "./temporal/countdown/branches/canon/branch.meta";
import { CountdownInlineStrip as temporal_countdown_canon_inlineStrip, meta as temporal_countdown_canon_inlineStripMeta } from "./temporal/countdown/branches/canon/inline-strip/inline-strip";
import { CountdownRingDial as temporal_countdown_canon_ringDial, meta as temporal_countdown_canon_ringDialMeta } from "./temporal/countdown/branches/canon/ring-dial/ring-dial";
import { CountdownUnitBlocks as temporal_countdown_canon_unitBlocks, meta as temporal_countdown_canon_unitBlocksMeta } from "./temporal/countdown/branches/canon/unit-blocks/unit-blocks";
import { meta as temporal_countdown_experimentalMeta } from "./temporal/countdown/branches/experimental/branch.meta";
import { CountdownFlipStack as temporal_countdown_experimental_flipStack, meta as temporal_countdown_experimental_flipStackMeta } from "./temporal/countdown/branches/experimental/flip-stack/flip-stack";

export const FOREST: SpeciesNode[] = [
  {
    key: "chrome",
    meta: species_chromeMeta,
    trees: [
    {
      key: "page-nav",
      species: "chrome",
      ref: "chrome/page-nav",
      meta: chrome_pageNavMeta,
      fixtures: chrome_pageNavFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: chrome_pageNavFixtures.DEFAULT_FIXTURE as string,
      frameAt: chrome_pageNavFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: chrome_pageNav_canonMeta,
        leaves: [
        {
          key: "brand-bar",
          ref: "canon/brand-bar",
          meta: chrome_pageNav_canon_brandBarMeta,
          Component: chrome_pageNav_canon_brandBar as ForestComponent,
        },
        {
          key: "glass-track",
          ref: "canon/glass-track",
          meta: chrome_pageNav_canon_glassTrackMeta,
          Component: chrome_pageNav_canon_glassTrack as ForestComponent,
        },
        {
          key: "pill-track",
          ref: "canon/pill-track",
          meta: chrome_pageNav_canon_pillTrackMeta,
          Component: chrome_pageNav_canon_pillTrack as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: chrome_pageNav_experimentalMeta,
        leaves: [
        {
          key: "floating-capsule",
          ref: "experimental/floating-capsule",
          meta: chrome_pageNav_experimental_floatingCapsuleMeta,
          Component: chrome_pageNav_experimental_floatingCapsule as ForestComponent,
        },
        ],
      },
      ],
    },
    {
      key: "pane-dock",
      species: "chrome",
      ref: "chrome/pane-dock",
      meta: chrome_paneDockMeta,
      fixtures: chrome_paneDockFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: chrome_paneDockFixtures.DEFAULT_FIXTURE as string,
      frameAt: chrome_paneDockFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: chrome_paneDock_canonMeta,
        leaves: [
        {
          key: "door-row",
          ref: "canon/door-row",
          meta: chrome_paneDock_canon_doorRowMeta,
          Component: chrome_paneDock_canon_doorRow as ForestComponent,
        },
        {
          key: "edge-strips",
          ref: "canon/edge-strips",
          meta: chrome_paneDock_canon_edgeStripsMeta,
          Component: chrome_paneDock_canon_edgeStrips as ForestComponent,
        },
        {
          key: "one-rail",
          ref: "canon/one-rail",
          meta: chrome_paneDock_canon_oneRailMeta,
          Component: chrome_paneDock_canon_oneRail as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: chrome_paneDock_experimentalMeta,
        leaves: [
        {
          key: "command-sheet",
          ref: "experimental/command-sheet",
          meta: chrome_paneDock_experimental_commandSheetMeta,
          Component: chrome_paneDock_experimental_commandSheet as ForestComponent,
        },
        ],
      },
      ],
    },
    {
      key: "section-tabs",
      species: "chrome",
      ref: "chrome/section-tabs",
      meta: chrome_sectionTabsMeta,
      fixtures: chrome_sectionTabsFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: chrome_sectionTabsFixtures.DEFAULT_FIXTURE as string,
      frameAt: chrome_sectionTabsFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: chrome_sectionTabs_canonMeta,
        leaves: [
        {
          key: "popover-menu",
          ref: "canon/popover-menu",
          meta: chrome_sectionTabs_canon_popoverMenuMeta,
          Component: chrome_sectionTabs_canon_popoverMenu as ForestComponent,
        },
        {
          key: "side-rail",
          ref: "canon/side-rail",
          meta: chrome_sectionTabs_canon_sideRailMeta,
          Component: chrome_sectionTabs_canon_sideRail as ForestComponent,
        },
        {
          key: "top-track",
          ref: "canon/top-track",
          meta: chrome_sectionTabs_canon_topTrackMeta,
          Component: chrome_sectionTabs_canon_topTrack as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: chrome_sectionTabs_experimentalMeta,
        leaves: [
        {
          key: "hover-dock",
          ref: "experimental/hover-dock",
          meta: chrome_sectionTabs_experimental_hoverDockMeta,
          Component: chrome_sectionTabs_experimental_hoverDock as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "commerce",
    meta: species_commerceMeta,
    trees: [
    {
      key: "product-card",
      species: "commerce",
      ref: "commerce/product-card",
      meta: commerce_productCardMeta,
      fixtures: commerce_productCardFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: commerce_productCardFixtures.DEFAULT_FIXTURE as string,
      frameAt: commerce_productCardFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: commerce_productCard_canonMeta,
        leaves: [
        {
          key: "detail-row",
          ref: "canon/detail-row",
          meta: commerce_productCard_canon_detailRowMeta,
          Component: commerce_productCard_canon_detailRow as ForestComponent,
        },
        {
          key: "spec-shelf",
          ref: "canon/spec-shelf",
          meta: commerce_productCard_canon_specShelfMeta,
          Component: commerce_productCard_canon_specShelf as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: commerce_productCard_experimentalMeta,
        leaves: [
        {
          key: "price-tag",
          ref: "experimental/price-tag",
          meta: commerce_productCard_experimental_priceTagMeta,
          Component: commerce_productCard_experimental_priceTag as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "disclosure",
    meta: species_disclosureMeta,
    trees: [
    {
      key: "expandable-card",
      species: "disclosure",
      ref: "disclosure/expandable-card",
      meta: disclosure_expandableCardMeta,
      fixtures: disclosure_expandableCardFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: disclosure_expandableCardFixtures.DEFAULT_FIXTURE as string,
      frameAt: disclosure_expandableCardFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: disclosure_expandableCard_canonMeta,
        leaves: [
        {
          key: "inline-detail",
          ref: "canon/inline-detail",
          meta: disclosure_expandableCard_canon_inlineDetailMeta,
          Component: disclosure_expandableCard_canon_inlineDetail as ForestComponent,
        },
        {
          key: "media-grid",
          ref: "canon/media-grid",
          meta: disclosure_expandableCard_canon_mediaGridMeta,
          Component: disclosure_expandableCard_canon_mediaGrid as ForestComponent,
        },
        {
          key: "row-list",
          ref: "canon/row-list",
          meta: disclosure_expandableCard_canon_rowListMeta,
          Component: disclosure_expandableCard_canon_rowList as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: disclosure_expandableCard_experimentalMeta,
        leaves: [
        {
          key: "full-bleed",
          ref: "experimental/full-bleed",
          meta: disclosure_expandableCard_experimental_fullBleedMeta,
          Component: disclosure_expandableCard_experimental_fullBleed as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "finding",
    meta: species_findingMeta,
    trees: [
    {
      key: "clip-picker",
      species: "finding",
      ref: "finding/clip-picker",
      meta: finding_clipPickerMeta,
      fixtures: finding_clipPickerFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: finding_clipPickerFixtures.DEFAULT_FIXTURE as string,
      frameAt: finding_clipPickerFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: finding_clipPicker_canonMeta,
        leaves: [
        {
          key: "one-column",
          ref: "canon/one-column",
          meta: finding_clipPicker_canon_oneColumnMeta,
          Component: finding_clipPicker_canon_oneColumn as ForestComponent,
        },
        {
          key: "quote-first",
          ref: "canon/quote-first",
          meta: finding_clipPicker_canon_quoteFirstMeta,
          Component: finding_clipPicker_canon_quoteFirst as ForestComponent,
        },
        {
          key: "shelf-rail",
          ref: "canon/shelf-rail",
          meta: finding_clipPicker_canon_shelfRailMeta,
          Component: finding_clipPicker_canon_shelfRail as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: finding_clipPicker_experimentalMeta,
        leaves: [
        {
          key: "deck",
          ref: "experimental/deck",
          meta: finding_clipPicker_experimental_deckMeta,
          Component: finding_clipPicker_experimental_deck as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "landing",
    meta: species_landingMeta,
    trees: [
    {
      key: "channel-hero",
      species: "landing",
      ref: "landing/channel-hero",
      meta: landing_channelHeroMeta,
      fixtures: landing_channelHeroFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: landing_channelHeroFixtures.DEFAULT_FIXTURE as string,
      frameAt: landing_channelHeroFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "broadcast",
        meta: landing_channelHero_broadcastMeta,
        leaves: [
        {
          key: "live-marquee",
          ref: "broadcast/live-marquee",
          meta: landing_channelHero_broadcast_liveMarqueeMeta,
          Component: landing_channelHero_broadcast_liveMarquee as ForestComponent,
        },
        ],
      },
      {
        key: "canon",
        meta: landing_channelHero_canonMeta,
        leaves: [
        {
          key: "split-dock",
          ref: "canon/split-dock",
          meta: landing_channelHero_canon_splitDockMeta,
          Component: landing_channelHero_canon_splitDock as ForestComponent,
        },
        {
          key: "stacked-billboard",
          ref: "canon/stacked-billboard",
          meta: landing_channelHero_canon_stackedBillboardMeta,
          Component: landing_channelHero_canon_stackedBillboard as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "motion",
    meta: species_motionMeta,
    trees: [
    {
      key: "aurora-headline",
      species: "motion",
      ref: "motion/aurora-headline",
      meta: motion_auroraHeadlineMeta,
      fixtures: motion_auroraHeadlineFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: motion_auroraHeadlineFixtures.DEFAULT_FIXTURE as string,
      frameAt: motion_auroraHeadlineFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: motion_auroraHeadline_canonMeta,
        leaves: [
        {
          key: "baseline",
          ref: "canon/baseline",
          meta: motion_auroraHeadline_canon_baselineMeta,
          Component: motion_auroraHeadline_canon_baseline as ForestComponent,
        },
        {
          key: "stacked-rule",
          ref: "canon/stacked-rule",
          meta: motion_auroraHeadline_canon_stackedRuleMeta,
          Component: motion_auroraHeadline_canon_stackedRule as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: motion_auroraHeadline_experimentalMeta,
        leaves: [
        {
          key: "orbit-glow",
          ref: "experimental/orbit-glow",
          meta: motion_auroraHeadline_experimental_orbitGlowMeta,
          Component: motion_auroraHeadline_experimental_orbitGlow as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "narrative",
    meta: species_narrativeMeta,
    trees: [
    {
      key: "step-reveal",
      species: "narrative",
      ref: "narrative/step-reveal",
      meta: narrative_stepRevealMeta,
      fixtures: narrative_stepRevealFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: narrative_stepRevealFixtures.DEFAULT_FIXTURE as string,
      frameAt: narrative_stepRevealFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: narrative_stepReveal_canonMeta,
        leaves: [
        {
          key: "numbered-rail",
          ref: "canon/numbered-rail",
          meta: narrative_stepReveal_canon_numberedRailMeta,
          Component: narrative_stepReveal_canon_numberedRail as ForestComponent,
        },
        {
          key: "wide-cards",
          ref: "canon/wide-cards",
          meta: narrative_stepReveal_canon_wideCardsMeta,
          Component: narrative_stepReveal_canon_wideCards as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: narrative_stepReveal_experimentalMeta,
        leaves: [
        {
          key: "stage-swap",
          ref: "experimental/stage-swap",
          meta: narrative_stepReveal_experimental_stageSwapMeta,
          Component: narrative_stepReveal_experimental_stageSwap as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "temporal",
    meta: species_temporalMeta,
    trees: [
    {
      key: "countdown",
      species: "temporal",
      ref: "temporal/countdown",
      meta: temporal_countdownMeta,
      fixtures: temporal_countdownFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: temporal_countdownFixtures.DEFAULT_FIXTURE as string,
      frameAt: temporal_countdownFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: temporal_countdown_canonMeta,
        leaves: [
        {
          key: "inline-strip",
          ref: "canon/inline-strip",
          meta: temporal_countdown_canon_inlineStripMeta,
          Component: temporal_countdown_canon_inlineStrip as ForestComponent,
        },
        {
          key: "ring-dial",
          ref: "canon/ring-dial",
          meta: temporal_countdown_canon_ringDialMeta,
          Component: temporal_countdown_canon_ringDial as ForestComponent,
        },
        {
          key: "unit-blocks",
          ref: "canon/unit-blocks",
          meta: temporal_countdown_canon_unitBlocksMeta,
          Component: temporal_countdown_canon_unitBlocks as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: temporal_countdown_experimentalMeta,
        leaves: [
        {
          key: "flip-stack",
          ref: "experimental/flip-stack",
          meta: temporal_countdown_experimental_flipStackMeta,
          Component: temporal_countdown_experimental_flipStack as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
];

export default FOREST;
