// GENERATED BY `pnpm sync` — DO NOT EDIT.
// Source of truth is the folder layout under src/trees/.
// Regenerate with: pnpm sync

import type { ForestComponent, SpeciesNode } from "@/lib/forest";

import { meta as species_chromeMeta } from "./chrome/species.meta";
import { meta as chrome_pageNavMeta } from "./chrome/page-nav/tree.meta";
import * as chrome_pageNavFixtures from "./chrome/page-nav/page-nav.fixtures";
import { meta as chrome_pageNav_canonMeta } from "./chrome/page-nav/branches/canon/branch.meta";
import { PageNavBrandBar as chrome_pageNav_canon_brandBar, meta as chrome_pageNav_canon_brandBarMeta } from "./chrome/page-nav/branches/canon/brand-bar/brand-bar";
import { PageNavGlassTrack as chrome_pageNav_canon_glassTrack, meta as chrome_pageNav_canon_glassTrackMeta } from "./chrome/page-nav/branches/canon/glass-track/glass-track";
import { PageNavPillTrack as chrome_pageNav_canon_pillTrack, meta as chrome_pageNav_canon_pillTrackMeta } from "./chrome/page-nav/branches/canon/pill-track/pill-track";
import { meta as chrome_pageNav_experimentalMeta } from "./chrome/page-nav/branches/experimental/branch.meta";
import { PageNavFloatingCapsule as chrome_pageNav_experimental_floatingCapsule, meta as chrome_pageNav_experimental_floatingCapsuleMeta } from "./chrome/page-nav/branches/experimental/floating-capsule/floating-capsule";
import { meta as chrome_sectionTabsMeta } from "./chrome/section-tabs/tree.meta";
import * as chrome_sectionTabsFixtures from "./chrome/section-tabs/section-tabs.fixtures";
import { meta as chrome_sectionTabs_canonMeta } from "./chrome/section-tabs/branches/canon/branch.meta";
import { SectionTabsPopoverMenu as chrome_sectionTabs_canon_popoverMenu, meta as chrome_sectionTabs_canon_popoverMenuMeta } from "./chrome/section-tabs/branches/canon/popover-menu/popover-menu";
import { SectionTabsSideRail as chrome_sectionTabs_canon_sideRail, meta as chrome_sectionTabs_canon_sideRailMeta } from "./chrome/section-tabs/branches/canon/side-rail/side-rail";
import { SectionTabsTopTrack as chrome_sectionTabs_canon_topTrack, meta as chrome_sectionTabs_canon_topTrackMeta } from "./chrome/section-tabs/branches/canon/top-track/top-track";
import { meta as chrome_sectionTabs_experimentalMeta } from "./chrome/section-tabs/branches/experimental/branch.meta";
import { SectionTabsHoverDock as chrome_sectionTabs_experimental_hoverDock, meta as chrome_sectionTabs_experimental_hoverDockMeta } from "./chrome/section-tabs/branches/experimental/hover-dock/hover-dock";
import { meta as species_landingMeta } from "./landing/species.meta";
import { meta as landing_channelHeroMeta } from "./landing/channel-hero/tree.meta";
import * as landing_channelHeroFixtures from "./landing/channel-hero/channel-hero.fixtures";
import { meta as landing_channelHero_broadcastMeta } from "./landing/channel-hero/branches/broadcast/branch.meta";
import { ChannelHeroLiveMarquee as landing_channelHero_broadcast_liveMarquee, meta as landing_channelHero_broadcast_liveMarqueeMeta } from "./landing/channel-hero/branches/broadcast/live-marquee/live-marquee";
import { meta as landing_channelHero_canonMeta } from "./landing/channel-hero/branches/canon/branch.meta";
import { ChannelHeroSplitDock as landing_channelHero_canon_splitDock, meta as landing_channelHero_canon_splitDockMeta } from "./landing/channel-hero/branches/canon/split-dock/split-dock";
import { ChannelHeroStackedBillboard as landing_channelHero_canon_stackedBillboard, meta as landing_channelHero_canon_stackedBillboardMeta } from "./landing/channel-hero/branches/canon/stacked-billboard/stacked-billboard";
import { meta as species_motionMeta } from "./motion/species.meta";
import { meta as motion_auroraHeadlineMeta } from "./motion/aurora-headline/tree.meta";
import * as motion_auroraHeadlineFixtures from "./motion/aurora-headline/aurora-headline.fixtures";
import { meta as motion_auroraHeadline_canonMeta } from "./motion/aurora-headline/branches/canon/branch.meta";
import { AuroraHeadlineBaseline as motion_auroraHeadline_canon_baseline, meta as motion_auroraHeadline_canon_baselineMeta } from "./motion/aurora-headline/branches/canon/baseline/baseline";
import { AuroraHeadlineStackedRule as motion_auroraHeadline_canon_stackedRule, meta as motion_auroraHeadline_canon_stackedRuleMeta } from "./motion/aurora-headline/branches/canon/stacked-rule/stacked-rule";
import { meta as motion_auroraHeadline_experimentalMeta } from "./motion/aurora-headline/branches/experimental/branch.meta";
import { AuroraHeadlineOrbitGlow as motion_auroraHeadline_experimental_orbitGlow, meta as motion_auroraHeadline_experimental_orbitGlowMeta } from "./motion/aurora-headline/branches/experimental/orbit-glow/orbit-glow";
import { meta as species_narrativeMeta } from "./narrative/species.meta";
import { meta as narrative_stepRevealMeta } from "./narrative/step-reveal/tree.meta";
import * as narrative_stepRevealFixtures from "./narrative/step-reveal/step-reveal.fixtures";
import { meta as narrative_stepReveal_canonMeta } from "./narrative/step-reveal/branches/canon/branch.meta";
import { StepRevealNumberedRail as narrative_stepReveal_canon_numberedRail, meta as narrative_stepReveal_canon_numberedRailMeta } from "./narrative/step-reveal/branches/canon/numbered-rail/numbered-rail";
import { StepRevealWideCards as narrative_stepReveal_canon_wideCards, meta as narrative_stepReveal_canon_wideCardsMeta } from "./narrative/step-reveal/branches/canon/wide-cards/wide-cards";
import { meta as narrative_stepReveal_experimentalMeta } from "./narrative/step-reveal/branches/experimental/branch.meta";
import { StepRevealStageSwap as narrative_stepReveal_experimental_stageSwap, meta as narrative_stepReveal_experimental_stageSwapMeta } from "./narrative/step-reveal/branches/experimental/stage-swap/stage-swap";
import { meta as species_temporalMeta } from "./temporal/species.meta";
import { meta as temporal_countdownMeta } from "./temporal/countdown/tree.meta";
import * as temporal_countdownFixtures from "./temporal/countdown/countdown.fixtures";
import { meta as temporal_countdown_canonMeta } from "./temporal/countdown/branches/canon/branch.meta";
import { CountdownInlineStrip as temporal_countdown_canon_inlineStrip, meta as temporal_countdown_canon_inlineStripMeta } from "./temporal/countdown/branches/canon/inline-strip/inline-strip";
import { CountdownRingDial as temporal_countdown_canon_ringDial, meta as temporal_countdown_canon_ringDialMeta } from "./temporal/countdown/branches/canon/ring-dial/ring-dial";
import { CountdownUnitBlocks as temporal_countdown_canon_unitBlocks, meta as temporal_countdown_canon_unitBlocksMeta } from "./temporal/countdown/branches/canon/unit-blocks/unit-blocks";
import { meta as temporal_countdown_experimentalMeta } from "./temporal/countdown/branches/experimental/branch.meta";
import { CountdownFlipStack as temporal_countdown_experimental_flipStack, meta as temporal_countdown_experimental_flipStackMeta } from "./temporal/countdown/branches/experimental/flip-stack/flip-stack";

export const FOREST: SpeciesNode[] = [
  {
    key: "chrome",
    meta: species_chromeMeta,
    trees: [
    {
      key: "page-nav",
      species: "chrome",
      ref: "chrome/page-nav",
      meta: chrome_pageNavMeta,
      fixtures: chrome_pageNavFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: chrome_pageNavFixtures.DEFAULT_FIXTURE as string,
      frameAt: chrome_pageNavFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: chrome_pageNav_canonMeta,
        leaves: [
        {
          key: "brand-bar",
          ref: "canon/brand-bar",
          meta: chrome_pageNav_canon_brandBarMeta,
          Component: chrome_pageNav_canon_brandBar as ForestComponent,
        },
        {
          key: "glass-track",
          ref: "canon/glass-track",
          meta: chrome_pageNav_canon_glassTrackMeta,
          Component: chrome_pageNav_canon_glassTrack as ForestComponent,
        },
        {
          key: "pill-track",
          ref: "canon/pill-track",
          meta: chrome_pageNav_canon_pillTrackMeta,
          Component: chrome_pageNav_canon_pillTrack as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: chrome_pageNav_experimentalMeta,
        leaves: [
        {
          key: "floating-capsule",
          ref: "experimental/floating-capsule",
          meta: chrome_pageNav_experimental_floatingCapsuleMeta,
          Component: chrome_pageNav_experimental_floatingCapsule as ForestComponent,
        },
        ],
      },
      ],
    },
    {
      key: "section-tabs",
      species: "chrome",
      ref: "chrome/section-tabs",
      meta: chrome_sectionTabsMeta,
      fixtures: chrome_sectionTabsFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: chrome_sectionTabsFixtures.DEFAULT_FIXTURE as string,
      frameAt: chrome_sectionTabsFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: chrome_sectionTabs_canonMeta,
        leaves: [
        {
          key: "popover-menu",
          ref: "canon/popover-menu",
          meta: chrome_sectionTabs_canon_popoverMenuMeta,
          Component: chrome_sectionTabs_canon_popoverMenu as ForestComponent,
        },
        {
          key: "side-rail",
          ref: "canon/side-rail",
          meta: chrome_sectionTabs_canon_sideRailMeta,
          Component: chrome_sectionTabs_canon_sideRail as ForestComponent,
        },
        {
          key: "top-track",
          ref: "canon/top-track",
          meta: chrome_sectionTabs_canon_topTrackMeta,
          Component: chrome_sectionTabs_canon_topTrack as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: chrome_sectionTabs_experimentalMeta,
        leaves: [
        {
          key: "hover-dock",
          ref: "experimental/hover-dock",
          meta: chrome_sectionTabs_experimental_hoverDockMeta,
          Component: chrome_sectionTabs_experimental_hoverDock as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "landing",
    meta: species_landingMeta,
    trees: [
    {
      key: "channel-hero",
      species: "landing",
      ref: "landing/channel-hero",
      meta: landing_channelHeroMeta,
      fixtures: landing_channelHeroFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: landing_channelHeroFixtures.DEFAULT_FIXTURE as string,
      frameAt: landing_channelHeroFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "broadcast",
        meta: landing_channelHero_broadcastMeta,
        leaves: [
        {
          key: "live-marquee",
          ref: "broadcast/live-marquee",
          meta: landing_channelHero_broadcast_liveMarqueeMeta,
          Component: landing_channelHero_broadcast_liveMarquee as ForestComponent,
        },
        ],
      },
      {
        key: "canon",
        meta: landing_channelHero_canonMeta,
        leaves: [
        {
          key: "split-dock",
          ref: "canon/split-dock",
          meta: landing_channelHero_canon_splitDockMeta,
          Component: landing_channelHero_canon_splitDock as ForestComponent,
        },
        {
          key: "stacked-billboard",
          ref: "canon/stacked-billboard",
          meta: landing_channelHero_canon_stackedBillboardMeta,
          Component: landing_channelHero_canon_stackedBillboard as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "motion",
    meta: species_motionMeta,
    trees: [
    {
      key: "aurora-headline",
      species: "motion",
      ref: "motion/aurora-headline",
      meta: motion_auroraHeadlineMeta,
      fixtures: motion_auroraHeadlineFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: motion_auroraHeadlineFixtures.DEFAULT_FIXTURE as string,
      frameAt: motion_auroraHeadlineFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: motion_auroraHeadline_canonMeta,
        leaves: [
        {
          key: "baseline",
          ref: "canon/baseline",
          meta: motion_auroraHeadline_canon_baselineMeta,
          Component: motion_auroraHeadline_canon_baseline as ForestComponent,
        },
        {
          key: "stacked-rule",
          ref: "canon/stacked-rule",
          meta: motion_auroraHeadline_canon_stackedRuleMeta,
          Component: motion_auroraHeadline_canon_stackedRule as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: motion_auroraHeadline_experimentalMeta,
        leaves: [
        {
          key: "orbit-glow",
          ref: "experimental/orbit-glow",
          meta: motion_auroraHeadline_experimental_orbitGlowMeta,
          Component: motion_auroraHeadline_experimental_orbitGlow as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "narrative",
    meta: species_narrativeMeta,
    trees: [
    {
      key: "step-reveal",
      species: "narrative",
      ref: "narrative/step-reveal",
      meta: narrative_stepRevealMeta,
      fixtures: narrative_stepRevealFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: narrative_stepRevealFixtures.DEFAULT_FIXTURE as string,
      frameAt: narrative_stepRevealFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: narrative_stepReveal_canonMeta,
        leaves: [
        {
          key: "numbered-rail",
          ref: "canon/numbered-rail",
          meta: narrative_stepReveal_canon_numberedRailMeta,
          Component: narrative_stepReveal_canon_numberedRail as ForestComponent,
        },
        {
          key: "wide-cards",
          ref: "canon/wide-cards",
          meta: narrative_stepReveal_canon_wideCardsMeta,
          Component: narrative_stepReveal_canon_wideCards as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: narrative_stepReveal_experimentalMeta,
        leaves: [
        {
          key: "stage-swap",
          ref: "experimental/stage-swap",
          meta: narrative_stepReveal_experimental_stageSwapMeta,
          Component: narrative_stepReveal_experimental_stageSwap as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
  {
    key: "temporal",
    meta: species_temporalMeta,
    trees: [
    {
      key: "countdown",
      species: "temporal",
      ref: "temporal/countdown",
      meta: temporal_countdownMeta,
      fixtures: temporal_countdownFixtures.ALL_FIXTURES as Record<string, unknown>,
      defaultFixture: temporal_countdownFixtures.DEFAULT_FIXTURE as string,
      frameAt: temporal_countdownFixtures.frameAt as (progress: number) => unknown,

      branches: [
      {
        key: "canon",
        meta: temporal_countdown_canonMeta,
        leaves: [
        {
          key: "inline-strip",
          ref: "canon/inline-strip",
          meta: temporal_countdown_canon_inlineStripMeta,
          Component: temporal_countdown_canon_inlineStrip as ForestComponent,
        },
        {
          key: "ring-dial",
          ref: "canon/ring-dial",
          meta: temporal_countdown_canon_ringDialMeta,
          Component: temporal_countdown_canon_ringDial as ForestComponent,
        },
        {
          key: "unit-blocks",
          ref: "canon/unit-blocks",
          meta: temporal_countdown_canon_unitBlocksMeta,
          Component: temporal_countdown_canon_unitBlocks as ForestComponent,
        },
        ],
      },
      {
        key: "experimental",
        meta: temporal_countdown_experimentalMeta,
        leaves: [
        {
          key: "flip-stack",
          ref: "experimental/flip-stack",
          meta: temporal_countdown_experimental_flipStackMeta,
          Component: temporal_countdown_experimental_flipStack as ForestComponent,
        },
        ],
      },
      ],
    },
    ],
  },
];

export default FOREST;
